project:
  type: book
  output-dir: _book

lang: en

bibliography: ../references/references.bib

book:
  title: "DIY-QuantiFluorONE-dsDNA-Fluorometer Workshop Booklet"
  author: "Open Science Project"
  date: today
  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/02_safety.qmd
    - chapters/03_theory_and_references.qmd
    - chapters/04_hardware_and_assembly.qmd
    - chapters/05_software_installation.qmd
    - chapters/06_getting_started_basic_operation_and_menu_navigation.qmd
    - chapters/07_calibration_suite_and_data_transfer.qmd
    - chapters/08_measurement_protocol.qmd
    - chapters/09_calibration_results_and_quality_control.qmd
    - chapters/10_validation_and_analytical_performance.qmd
    - chapters/11_troubleshooting.qmd
    - chapters/12_workshop_exercises_and_checklists.qmd
    - chapters/13_references.qmd
  appendices:
    - appendices/appendices.qmd

format:
  html:
    toc: true
    number-sections: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
    use-rsvg-convert: false
 