project:
  type: book

book:
  title: "DIY-QuantiFluorONE-dsDNA-Fluorometer Workshop Booklet"
  author: "Open Science Project"
  date: today
  chapters:
    - index.qmd
    - chapters/04_hardware_and_assembly.qmd
    - chapters/05_getting_started_basic_operation_and_menu_navigation.qmd
    - chapters/06_calibration_suite_webapp.qmd
    - chapters/07_installing_circuitpython_bootloader_and_firmware.qmd

format:
  html:
    toc: true
    number-sections: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
